### ISSUE TITLE
NameError: name 'pytex' is not defined

### ISSUE THREAD

**Issue by jowe19** [Cadair/texfigure#4]
Hello.

I try this solution in order to include easily a lot of figures in a tex document. Unfortunately I get the following error and I am not able to fix it.

----  Messages for pylab:default:default  ----
  Traceback (most recent call last):
* PythonTeX stderr - error on line 26:
    File "<outputdir>/pylab_default_default.py", line 70, in <module>
      name = savefig()
    File "/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 689, in savefig
      res = fig.savefig(*args, **kwargs)
  TypeError: savefig() missing 1 required positional argument: 'fname'

\documentclass[11pt]{article}
\usepackage{pythontex}

\begin{pythontexcustomcode}[begin]{pylab}
sys.path.append('/Users/.../DevoirsTPs/TPInfo/')
from python_preambule import *
from matplotlib.pyplot import *
\end{pythontexcustomcode}
    
\begin{document}

ABCDE

\begin{pylabcode}
x = linspace(0, pi)
plt.plot(x, sin(x), label='sin(x)')
plt.plot(x, cos(x), label='cos(x)')
name = savefig()
fig = latex_figure(name)
\end{pylabcode}
\pylab{fig}

\end{document}

**Comment by Cadair** [comment]
pytex is part of pythontex, I would imagine that it is only defined inside the scope of the latex document, i.e. not accessible from your import. I would suggest you import a function and then call it with the pytex global i.e.
```
from python_preamble import setup
setup(pytex)
```
